
AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Semicolon:
  AllowAsExpressionSeparator: true
